### ISSUE TITLE
SU2 does not compile with the provided catch2 on newer ubuntu linux distributions

### ISSUE THREAD

**Issue by bigfooted** [su2code/SU2#1724]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*
I say "newer ubuntu linux distributions" cause that's what I have, but this is probably due to some compiler/glibc change that will affect all newer systems that upgrade glibc.
When compiling with -Denable-tests=true, we are using catch2.hpp from the externals/ folder. This catch version is v2.11.1. However, the behavior of glibc(? what I understood from some bug reports) changed somewhere last year, specifically MINSIGSTKSZ became non-constant, leading to the following errors below. To prevent this issue, catch needs to be upgraded to version>2.13.5. In my case, recompiling with the system version of catch2-2.13.8-1 was sufficient to be able to compile again. 

```
 FAILED: UnitTests/test_driver.p/test_driver.cpp.o 
/usr/bin/mpicxx.mpich -IUnitTests/test_driver.p -IUnitTests -I../UnitTests -ISU2_CFD/src -I../SU2_CFD/src -ICommon/src -I../Common/src -I../externals/CLI11 -I../externals/cgns/adf -I../externals/cgns/adfh -Iexternals/cgns -I../externals/cgns -Iexternals/cgns/hdf5 -I../externals/cgns/hdf5 -I../externals/metis/include -I../externals/metis/GKlib -I../externals/metis/libmetis -I../externals/parmetis/include -I../externals/parmetis/libparmetis -I../externals/mel -I../externals/catch2 -I/usr/include/x86_64-linux-gnu/mpich -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++11 -O3 -fPIC -Wno-empty-body -Wno-unused-parameter -Wno-deprecated-declarations -Wno-non-virtual-dtor -DHAVE_CGNS -DNDEBUG -DHAVE_MPI -DHAVE_METIS -DHAVE_PARMETIS -MD -MQ UnitTests/test_driver.p/test_driver.cpp.o -MF UnitTests/test_driver.p/test_driver.cpp.o.d -o UnitTests/test_driver.p/test_driver.cpp.o -c ../UnitTests/test_driver.cpp
In file included from /usr/include/signal.h:328,
                 from ../externals/catch2/catch.hpp:7955,
                 from ../UnitTests/test_driver.cpp:32:
../externals/catch2/catch.hpp:10735:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10735 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from ../externals/catch2/catch.hpp:7955,
                 from ../UnitTests/test_driver.cpp:32:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from ../UnitTests/test_driver.cpp:32:
../externals/catch2/catch.hpp:10794:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10794 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
```

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*
In my case, this issue occurred when I upgraded my kubuntu version to 22.04
some info:
https://github.com/catchorg/Catch2/issues/2178
https://github.com/catchorg/Catch2/issues/2421

**Desktop (please complete the following information):

Project version: 7.3.1 "Blackbird"
C compiler for the host machine: /usr/bin/mpicc.mpich (gcc 11.2.0 "gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: /usr/bin/mpicc.mpich ld.bfd 2.38
C++ compiler for the host machine: /usr/bin/mpicxx.mpich (gcc 11.2.0 "g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C++ linker for the host machine: /usr/bin/mpicxx.mpich ld.bfd 2.38

**Comment by pcarruscag** [comment]
Let's bump it up then, it's just a header file and license we need to replace in externals.

**Comment by bigfooted** [comment]
Pull request #1726

**Comment by bigfooted** [comment]
closed by merging #1726
