### ISSUE TITLE
cgns compilation error for macOS after #1500

### ISSUE THREAD

**Issue by bigfooted** [su2code/SU2#1507]
reported by @jtlau 

> I'm having an issue compiling on macOS. I get an error after "./meson.py build":
> 
> Configuring H5pubconf.h using configuration
> 
> externals/cgns/hdf5/meson.build:662:0: ERROR: #mesondefine does not contain exactly two tokens: #cmakedefine H5_HAVE_WINDOWS @H5_HAVE_WINDOWS@
> 
> I'm not sure where to go from there... since I don't need cgns I workaround this by disabling it...
> LMK if you need the full configure error

**Comment by pcarruscag** [comment]
The windows images are also not being created:
https://github.com/su2code/SU2/runs/4875423564?check_suite_focus=true

@MicK7 can you have a look please?

**Comment by MicK7** [comment]
Which meson version is used ?

**Comment by pcarruscag** [comment]
This one 29ef4478df6d3aaca40c7993f125b29409be1de2
Yes it's possible, which one do we need?

**Comment by MicK7** [comment]
I think that 5e9b709ad0b34d8ac920dff057a5361080c0889b would be enough for the formatter of "cmake@" that leads to an error.

**Comment by bigfooted** [comment]
@jtlau @pcarruscag is this issue now solved with the latest PR?

**Comment by pcarruscag** [comment]
I don't have a mac :blush:

**Comment by jtlau** [comment]
@bigfooted @pcarruscag Yes! I didn't notice the tag. But yes, as of today SU2 will compile on macOS (11.2.1). Thanks for the fix!
